name: ResourcesWorldResetter
version: '3.0.0'
main: com.lozaine.ResourceWorldResetter.ResourceWorldResetter
api-version: '1.21'
depend: [Multiverse-Core]
author: Lozaine
description: A plugin to reset the resources world at regular intervals.

commands:
  rwrgui:
    description: "Open the Resource World Reset GUI"
    usage: "/rwrgui"
    permission: "resourceworldresetter.admin"

  reloadrwr:
    description: "Reload the ResourceWorldResetter plugin"
    usage: "/reloadrwr"
    permission: "resourceworldresetter.admin"

  resetworld:
    description: "Force reset the resource world"
    usage: "/resetworld"
    permission: "resourceworldresetter.admin"

  rwrregion:
    description: "Manage region-based resets"
    usage: "/rwrregion <enable|disable|list|add <rx> <rz>|remove <rx> <rz>|addhere>"
    permission: "resourceworldresetter.admin"