name: ResourcesWorldResetter
version: '2.3.0-UNRELEASED'
main: com.lozaine.ResourceWorldResetter.ResourceWorldResetter
api-version: '1.21'  # Updated to 1.21
depend: [Multiverse-Core]
author: Lozaine
description: A plugin to reset the resources world at regular intervals.

commands:
  setworld:
    description: "Set the resource world name"
    usage: "/setworld <worldname>"
    permission: "resourceworldresetter.admin"

  setresetinterval:
    description: "Set the reset interval in hours"
    usage: "/setresetinterval <hours>"
    permission: "resourceworldresetter.admin"

  setrestarttime:
    description: "Set the server restart time"
    usage: "/setrestarttime <hour>"
    permission: "resourceworldresetter.admin"

  resetworld:
    description: "Force reset the resource world"
    usage: "/resetworld"
    permission: "resourceworldresetter.admin"

  reloadworldresetter:
    description: "Reload the ResourceWorldResetter plugin"
    usage: "/reloadworldresetter"
    permission: "resourceworldresetter.admin"

  resourcegui:
    description: "Open the Resource World Admin GUI"
    usage: "/resourcegui"
    permission: "resourceworldresetter.admin"

